// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvzzmxilsnwmbjuivhvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52enpteGlsc253bWJqdWl2aHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzMDgwMTYsImV4cCI6MjA4OTg4NDAxNn0.CtNP4wf8P36qBSUg0vRAwofSuF__WOVlWKr52I-zHMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});